language: C

install:
  - CHANNEL=http://eupsforge.net/conda/dev ./setup/travis_install.sh lsst-sims nose pandas
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source eups-setups.sh
  - setup lsst_sims
  - eups declare -r . light_curve_service -t current
  - setup light_curve_service

cache:
  directories:
  - $HOME/miniconda.tarball

script:
  - nosetests
